# Gradle Properties
# Copyright 2024-2025 MicroEJ Corp. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be found with this software.

# When enabled (true), skips the kernel build during the feature build process.
# Use this only if the kernel has already been built beforehand.
feature.skip.build.kernel=false